### ISSUE TITLE
melpa package

### ISSUE THREAD

**Issue by salotz** [seanfarley/xonsh-mode#1]
A melpa package would be nice :)

**Comment by salotz** [comment]
Would you be alright with me doing this from my fork?

**Comment by seanfarley** [comment]
Sorry for the delay!

I was planning on uploading to melpa after letting this bake a while; which I'm happy enough with it now to do so. Why not just send me a PR from your fork for the commits you have now? I think most of them make sense so we can discuss in a code review if you prefer :-)

**Comment by salotz** [comment]
No problem, thanks for making this. I've been "baking" it for a few weeks or so too and it seems to do alright. PR #2

**Comment by salotz** [comment]
Thanks for your work @seanfarley https://melpa.org/#/xonsh-mode.
